services:
  golizilla-api:
    container_name: golizilla-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .env:/app/.env
      - ./template:/app/template
    depends_on:
      - golizilla-db

  golizilla-db:
    container_name: golizilla-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  golizilla-mongodb:
    container_name: golizilla-mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongoDB_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  golizilla-grafana:
    image: grafana/grafana:latest
    container_name: golizilla-grafana
    ports:
      - "${GF_PORT}:3000" 
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_PASSWORD}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD}
    depends_on:
      - golizilla-mongodb

  golizilla-log-server:
    build:
      context: ./persistence/logger/server
    container_name: golizilla-log-server
    # ports:
    #   - "5000:${LOGGER_PORT}"
    depends_on:
      - golizilla-mongodb
    environment:
      MONGO_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@golizilla-mongodb:27017
      LOGGER_PORT: ${LOGGER_PORT}
      GF_HOST: ${GF_HOST}
      GF_PORT: ${GF_PORT}


volumes:
  db_data:
  mongoDB_data:
  grafana_data:

